baseurl = "https://jason-lewis.com/"
languageCode = "en-us"
title = "Jason Lewis' personal site"
theme = "hugo-creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Jason Lewis"

		[params.navigation.links]
			about     = "Strengths"
			services  = "At a Glance"
#			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Right Brain, Left Brain"
		subtitle   = "[Jason Lewis](//linkedin.com/in/jasonlewismedia): I am passionate about the interplay between art & science, technology & media, & bringing diverse people together to achieve things no one has done before."
		buttonText = "Learn More About Me"


	# About section
	[params.about]
		headline    = "Adaptability, Creativity, Innovation, Grit, Empathy & Continuous Learning"
		description = "I grew up in Latin America, Africa, Asia, & the Middle East & it taught me appreciation for diversity & how to quickly adapt, learn, and take on change successfully. I credit this multi-cultural education for my ability to quickly dive into complex technology projects, engage successfully with cross-functional stakeholders, & architect solutions."
	#	buttonText  = "Traveling is good!"


	# Service section
	[params.services]
		headline = "At a glance"

        [[params.services.list]]
			icon = "fa-users"
			title = "Leadership"
			description = "Building high performing cross-functional teams & providing Solutions Architecture support"

        [[params.services.list]]
            icon = "fa-code-branch"
            title = "Patents"
            description = "5 patents for Media, Video Streaming, & Internet of Things (IoT) systems & methods"

		[[params.services.list]]
            icon = "fas fa-brain"
            title = "Machine Learning"
            description = "Leveraging & Teaching others about Data Science, AI/ML, & Automation"

        [[params.services.list]]
            icon = "fa-code"
            title = "Entrepreneur"
            description = "Launched v.1 products with Emerging Technology • Founded my own Media Agency in Africa"

        [[params.services.list]]
            icon = "fa-globe"
            title = "Global Experience"
            description = "Multi-cultural experience living & working internationally"

        [[params.services.list]]
            icon = "fa-film"
            title = "Media Production"
            description = "Experienced in shooting, video editing, motion graphics, design, & online media"

        [[params.services.list]]
            icon = "fa-camera"
            title = "Photography"
            description = "Shooting professionally or just for fun, I'll always have a passion for this artform"

		[[params.services.list]]
            icon = "fa-skiing"
            title = "Outdoors"
            description = "I love biking, climbing, skiing, paddleboarding, & backpacking when not hacking out code"




    # Portfolio modals
#	[params.portfolio.modal]
#        client = "Client"
#        date = "Date"
#        category = "Category"
#        buttonText = "Close"

    # Aside section
#	[params.aside]
#		headline = "Get the Creative Theme for Hugo"
#
#		[params.aside.button]
#			text = "Download now"
#			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Want to get in touch?"
		description = "Send me a quick note or connect with me on LinkedIn: [@jasonlewismedia](https://linkedin.com/in/jasonlewismedia/)"
		# phone = "TwoZeroSix-FourNineFive-TwoOneZeroThree"
		email = "code@jason-lewis.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""